services:
  discord-bot:
    build:
      context: .
      dockerfile: discord_bot/dockerfile
    container_name: discord-bot
    restart: always
    volumes:
      - type: bind
        source: ./src
        target: /app
      - type: bind
        source: ./logs
        target: /logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
    networks:
      - discord-net

  scraper:
    build:
      context: .
      dockerfile: scraper/dockerfile
    container_name: scraper
    restart: always
    volumes:
      - type: bind
        source: ./src/scraper
        target: /app
      - type: bind
        source: ./logs
        target: /logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
    networks:
      - discord-net

networks:
  discord-net:
    driver: bridge
