"""add tables FBPost and FBImage

資料庫遷移檔案 - 自動生成
專案：爬蟲系統
作者：系統自動生成

Revision ID: 015d8cb32801
Revises: 
Create Date: 2025-10-27 15:21:13.081881+08:00

此檔案包含：
- upgrade(): 升級資料庫結構的操作
- downgrade(): 回滾到上一版本的操作

注意：請勿手動修改版本識別資訊
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015d8cb32801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升級資料庫結構

    此函式包含將資料庫從上一版本升級到當前版本的所有操作
    如：建立表格、新增欄位、建立索引等
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_md', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fb_posts_post_id'), 'fb_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_fb_posts_url'), 'fb_posts', ['url'], unique=True)
    op.create_table('fb_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fb_post_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fb_post_id'], ['fb_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fb_post_id', 'image_url', name='unique_post_image')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滾資料庫結構

    此函式包含將資料庫從當前版本回滾到上一版本的所有操作
    如：刪除表格、移除欄位、刪除索引等
    注意：回滾操作可能會導致資料遺失
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_images')
    op.drop_index(op.f('ix_fb_posts_url'), table_name='fb_posts')
    op.drop_index(op.f('ix_fb_posts_post_id'), table_name='fb_posts')
    op.drop_table('fb_posts')
    # ### end Alembic commands ###
